import React, { useState, useRef } from 'react';
import { QrReader } from 'react-qr-reader';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import { Scanner } from '@yudiel/react-qr-scanner';

export default function Scan() {
  const router = useRouter();
  const [data, setData] = useState('No result');
  const [showModal, setShowModal] = useState(false);
  const qrRef = useRef(null);

  const handleScan = (result, error) => {
    if (!!result) {
      setData(result?.text);
      setShowModal(true);
      qrRef.current.stop();
    }

    if (!!error) {
      console.info(error);
    }
  };

  const handleCloseModal = () => {
    setShowModal(false);
    router.reload();
  };

  const handleOK = async (url) => {
    const res = await axios.get(url, {
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
    });
    alert(JSON.stringify(res, null, 2));
    router.reload();
  };

  return (
    <>
      <Head>
        <title>QR Scan</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col mt-[5rem] justify-center items-center'>
        <div className='flex flex-col justify-center items-center'>
          <h1 className='text-4xl font-bold mb-4'>QR Scanner</h1>
          <div>
            <Scanner
              onScan={(result) => {
                console.log(result);
                handleOK(result[0].rawValue);
              }}
              classNames='lg:h-[400px] lg:w-[400px] h-[300px] w-[300px]'
            />
          </div>
          <Link
            href={`/`}
            className=' bg-yellow-200 m-4 text-md rounded-md px-4 py-2 hover:underline'
          >
            Back to home..
          </Link>
          {showModal && (
            <div className='fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center'>
              <div className='bg-white rounded-md p-4'>
                <p className='text-xl font-bold mb-2'>Scanned data:</p>
                <p>{data}</p>
                <button
                  className='bg-gray-200 text-gray-800 px-4 py-2 rounded-md mt-4 hover:bg-gray-300'
                  onClick={handleCloseModal}
                >
                  Close
                </button>
                <button
                  className='bg-gray-200 text-gray-800 px-4 py-2 rounded-md mx-4 mt-4 hover:bg-gray-300'
                  onClick={handleOK}
                >
                  Ok
                </button>
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
