import React from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import { Scanner } from '@yudiel/react-qr-scanner';

export default function Scan() {
  const router = useRouter();

  const handleScan = async (scannedData) => {
    try {
      console.log('Scanned data:', scannedData);
      const res = await axios.get(scannedData, {
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
      });
      alert(JSON.stringify(res, null, 2));
      router.reload();
    } catch (error) {
      console.error('Error fetching data:', error);
      alert('Error fetching data: ' + error.message);
      router.reload();
    }
  };

  return (
    <>
      <Head>
        <title>QR Scan</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col mt-[5rem] justify-center items-center'>
        <div className='flex flex-col justify-center items-center'>
          <h1 className='text-4xl font-bold mb-4'>QR Scanner</h1>
          <div>
            <Scanner
              onScan={(result) => {
                if (result && result[0]) {
                  handleScan(result[0].rawValue);
                }
              }}
              classNames='lg:h-[400px] lg:w-[400px] h-[300px] w-[300px]'
            />
          </div>
          <Link
            href={`/`}
            className=' bg-yellow-200 m-4 text-md rounded-md px-4 py-2 hover:underline'
          >
            Back to home..
          </Link>
        </div>
      </main>
    </>
  );
}
